apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    app: api
spec:
  type: LoadBalancer
  ports:
    - name: api-svc-port
      port: 80
      targetPort: api-ctr-port
  selector:
    app: api
    tier: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
    tier: frontend
spec:
  selector:
    matchLabels:
      app: api
      tier: frontend
  strategy:
    type: RollingUpdate
  replicas: 3
  template:
    metadata:
      labels:
        app: api
        tier: frontend
    spec:
      containers:
        - name: api-ctr
          image: ajagnic/sample-api:latest
          resources:
            requests:
              memory: 40Mi
              cpu: 50m
            limits:
              memory: 150Mi
              cpu: 100m
          env:
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: api-config
                  key: uri
          ports:
            - name: api-ctr-port
              containerPort: 5001