apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    app: api
spec:
  type: NodePort
  ports:
    - name: api-svc-port
      targetPort: api-ctr-port
  selector:
    app: api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deploy
  labels:
    app: api
spec:
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api-ctr
          image: ajagnic/sample-api:0.0.1
          imagePullPolicy: IfNotPresent
          env:
            - name: MONGODB_URI
              value: mongodb://admin:admin@db:27017
          ports:
            - name: api-ctr-port
              containerPort: 5001
  strategy:
    type: RollingUpdate
  replicas: 1