apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    app: api
spec:
  type: LoadBalancer
  ports:
    - name: api-svc-port
      port: 80
      targetPort: api-ctr-port
  selector:
    app: api
    tier: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
    tier: frontend
spec:
  selector:
    matchLabels:
      app: api
      tier: frontend
  strategy:
    type: RollingUpdate
  replicas: 5
  template:
    metadata:
      labels:
        app: api
        tier: frontend
    spec:
      containers:
        - name: api-ctr
          image: ajagnic/sample-api:0.0.1
          imagePullPolicy: IfNotPresent
          env:
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: api-config
                  key: uri.txt
          ports:
            - name: api-ctr-port
              containerPort: 5001