apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    app: api
spec:
  ports:
    - name: db-svc-port
      port: 27017
  clusterIP: None
  selector:
    app: api
    tier: backend
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db
  labels:
    app: api
    tier: backend
spec:
  selector:
    matchLabels:
      app: api
      tier: backend
  serviceName: db
  replicas: 1
  template:
    metadata:
      labels:
        app: api
        tier: backend
    spec:
      containers:
        - name: mongo-ctr
          image: mongo:3.6-xenial
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: api-config
                  key: username.txt
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: api-config
                  key: password.txt
          ports:
            - name: mongo-ctr-port
              containerPort: 27017
          volumeMounts:
            - name: mongo
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: mongo
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 5Gi