apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-db-pvc
  labels:
    app: api
    tier: backend
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi