version: '3.8'
services:

  db:
    image: mongo:3.6-xenial
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    networks:
      - app
    expose:
      - '27017'
    volumes:
      - mongo-db:/data/db
      - mongo-config:/data/configdb

  api:
    build: .
    image: api:0.0.1
    environment:
      - MONGODB_URI=mongodb://admin:admin@db:27017
    networks:
      - app
    ports:
      - 5001:5001
    depends_on:
      - db

networks:
  app:
volumes:
  mongo-db:
  mongo-config: